### PR TITLE
Run `elm make` instead of `elm-make` for 0.19 compatibility

### PR DESCRIPTION
**Pull request by rtfeldman**
I know you're looking for maintainers, but I ran into this when trying out the workshop on 0.19 and figured I'd try making a PR for it anyway! 😄

### CODE REVIEW

**Comment by rtfeldman** [comment]
@architectcodes Dropped the whitespace commit! 👍

**Comment by wking-io** [comment]
This is going to fail. I tested the changes locally and since the new elm platform has make as an arg spawnSync will fail. You can get this working by changing the concept of `--path-to-elm-make` to `--path-to-elm` and then force `make` as part of the arg list in `elm-live.js`

```js
// default setup in parse-args.js
const defaults = {
  port: 8000,
  open: false,
  help: false,
  recover: true,
  pathToElm: "elm",
  host: "localhost",
  dir: ".",
  pushstate: false,
  version: false
};

// elm make command in elm-live.js
const elmMake = spawnSync(args.pathToElm, ["make", ...args.elmMakeArgs], {
      stdio: [inputStream, outputStream, outputStream]
    });
```

Then obviously you would just need to update `pathToElmMake` property to `pathToElm`. This will get it working without losing the ability of users to specify a custom path to the elm binary.

What do you think @rtfeldman and @architectcodes ?

**Comment by wking-io** [comment]
I can make a PR if it is easier, but figured since this was already going on here it would be more trouble for you both.

**Comment by architectcodes** [comment]
Wow, thanks for the valuable thoughts @wking-io! Would github allow you to push that as a commit to this PR? That would be super helpful in bringing elm-live to 0.19 projects fast 🏆

**Comment by wking-io** [comment]
I don't think I can, but I can make a new PR that combines Richard's updates with mine

**Comment by wking-io** [comment]
Also, I noticed that you are looking for a maintainer and I would also be happy take that responsibility over. I could make this launch to 0.19 the first project doing that.

**Comment by architectcodes** [comment]
Man that sounds A-MA-ZING!

**Comment by architectcodes** [comment]
Please do submit the PR as you suggested. I’ll reach out on email right away so we can roll things out together when the PR is ready and so we can talk everything through. See you there!

**Comment by wking-io** [comment]
@architectcodes if you could add me as a contributor then I can make the change directly to this repo. That way I do not have to fork and then worry about that throughout the transition period if that is okay with you!

**Comment by wking-io** [comment]
Headed to dinner but if you are cool with that I will make that PR when I get back. :)

**Comment by architectcodes** [comment]
Makes sense, welcome to the Collaborators table! Just sending you an email with all next steps so we can get things rolling 🚀

**Comment by wking-io** [comment]
Hey @rtfeldman, we went ahead and got everything 0.19 ready in another PR just wanted to give you a heads up why I am going to go ahead and close this one out! Thank you for the help!

**Pull request closed without merging**
