### PR TITLE
Upgrade to elm 19

### PR DESCRIPTION
**Pull request by wking-io**
Hey @architectcodes!

Figured out the style issues and just turned off auto-format on my editor. Let me know what you think of the PR!

The main changes were:

1. Moved elm command to be just `elm` and force added in the `make` argument to the `spawnSync` function.
2. Updated the naming of the `--path-to-elm-make` to better reflect the new binary shipped by Elm.
3. Updated tests to capture the change in the base command run by `spawnSync`

### CODE REVIEW

**Comment by billperegoy** [comment]
This looks very similar to a PR I was just working on. I should have looked before I started working myself. This looks great to me. I'd love to see a real release of this!

**Comment by architectcodes** [comment]
Thanks a lot @billperegoy, that’s great! We’re working with @wking-io to get this released asap as a pre-release version.

Even though this does the job perfectly for Elm 0.18-like scenarios, supporting things like `Browser.document` and `Browser.application` will require a little bit more work. If you want to join the effort of getting things fully up to scratch, we’ll be doing a pair programming session tomorrow: https://calendar.google.com/calendar/b/0?cid=NGtxZ2kyb3Jocjk4cjFnYm84ZW5vNjV2M2tAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ. It’d be great to make a mob programming session out of that, as I think there’s enough work to divide nicely among 2-3 people 🙂

**Comment by architectcodes** [comment]
Would you like to join us @billperegoy?

**Comment by billperegoy** [comment]
Hi. I won't be able to make tomorrow's pairing session as I will be traveling but if there any open issues after that session, please ping me and I'll try to help out!

**Pull request merged**
